version: '3'

services:

  db:
    image: postgres
    networks:
      - main

  backend:
    container_name: backend_dev
    build: ./backend
    command: ./scripts/start_dev.sh
    volumes:
      - ./backend:/code
      - django-static:/backend/static
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    networks:
      - main

  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
    command: ./scripts/start_dev.sh
    volumes:
      - ./frontend:/frontend_app/:ro
      - /frontend_app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - db
    networks:
      - main

  nginx:
    container_name: nginx_dev
    build:
      context: .
      dockerfile: nginx/dev/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/dev/dev.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
    networks:
      - main

volumes:
  django-static:

networks:
  main:
    driver: bridge
