version: '3'

services:

  db:
    image: postgres

  backend:
    container_name: backend_dev
    build: ./backend
    command: ./scripts/start_dev.sh
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
