export const AUTH_SIGN_UP = 'AUTH_SIGN_UP'
export const AUTH_SIGN_UP_ERROR = 'AUTH_SIGN_UP_ERROR'

export const AUTH_ACCOUNT_ACTIVATE = 'AUTH_ACCOUNT_ACTIVATE'
export const AUTH_ACCOUNT_ACTIVATE_SUCCESS = 'AUTH_ACCOUNT_ACTIVATE_SUCCESS'
export const AUTH_ACCOUNT_ACTIVATE_ERROR = 'AUTH_ACCOUNT_ACTIVATE_ERROR'


export const AUTH_LOG_IN = 'AUTH_LOG_IN'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_TOKEN_CREATE = 'AUTH_TOKEN_CREATE'
export const AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH'
export const AUTH_TOKEN_VERIFY = 'AUTH_TOKEN_VERIFY'


export const TEST_ACTION = 'TEST_ACTION'

