export const AUTH_SIGN_UP = 'AUTH_SIGN_UP'
export const AUTH_SIGN_UP_SUCCESS = 'AUTH_SIGN_UP_SUCCESS'
export const AUTH_SIGN_UP_ERROR = 'AUTH_SIGN_UP_ERROR'

export const AUTH_ACCOUNT_ACTIVATE = 'AUTH_ACCOUNT_ACTIVATE'
export const AUTH_ACCOUNT_ACTIVATE_SUCCESS = 'AUTH_ACCOUNT_ACTIVATE_SUCCESS'
export const AUTH_ACCOUNT_ACTIVATE_ERROR = 'AUTH_ACCOUNT_ACTIVATE_ERROR'

// Password reset
export const AUTH_PASSWORD_RESET = 'AUTH_PASSWORD_RESET'
export const AUTH_PASSWORD_RESET_SUCCESS = 'AUTH_PASSWORD_RESET_SUCCESS'
export const AUTH_PASSWORD_RESET_ERROR = 'AUTH_PASSWORD_RESET_ERROR'
export const AUTH_PASSWORD_RESET_CONFIRM = 'AUTH_PASSWORD_RESET_CONFIRM'
export const AUTH_PASSWORD_RESET_CONFIRM_SUCCESS = 'AUTH_PASSWORD_RESET_CONFIRM_SUCCESS'
export const AUTH_PASSWORD_RESET_CONFIRM_ERROR = 'AUTH_PASSWORD_RESET_CONFIRM_ERROR'

export const AUTH_LOG_IN = 'AUTH_LOG_IN'
export const AUTH_LOG_IN_SUCCESS = 'AUTH_LOG_IN_SUCCESS'
export const AUTH_LOG_IN_ERROR = 'AUTH_LOG_IN_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_TOKEN_CREATE = 'AUTH_TOKEN_CREATE'
export const AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH'
export const AUTH_TOKEN_VERIFY = 'AUTH_TOKEN_VERIFY'

// Test
export const TEST_ACTION = 'TEST_ACTION'
