export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_TOKEN_CREATE = 'AUTH_TOKEN_CREATE'
export const AUTH_TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH'
export const AUTH_TOKEN_VERIFY = 'AUTH_TOKEN_VERIFY'


export const TEST_ACTION = 'TEST_ACTION'

