export const DASHBOARD_STATS_NEW_AND_OLD_LOAD = 'DASHBOARD_STATS_NEW_AND_OLD_LOAD';
export const DASHBOARD_STATS_EISENHOWER_MATRIX_LOAD = 'DASHBOARD_STATS_EISENHOWER_MATRIX_LOAD';
export const DASHBOARD_STATS_STATUS_LIST_LOAD = 'DASHBOARD_STATS_STATUS_LIST_LOAD';
export const DASHBOARD_STATS_STATUSES_CHART= 'DASHBOARD_STATS_STATUSES_CHART';
