export const SETTINGS_GET_TASK_STATUS_LIST = 'SETTINGS_GET_TASK_STATUS_LIST';
export const SETTINGS_UPDATE_STATUS = 'SETTINGS_UPDATE_STATUS';
export const SETTINGS_CREATE_STATUS = 'SETTINGS_CREATE_STATUS';
