export const TASKS_LOAD_TASK_LIST = 'TASKS_LOAD_TASK_LIST'
export const TASKS_LOAD_TASK_LIST_SUCCESS = 'TASKS_LOAD_TASK_LIST_SUCCESS'

export const TASKS_LOAD_CATEGORY_LIST = 'TASKS_LOAD_CATEGORY_LIST'
export const TASKS_LOAD_CATEGORY_LIST_SUCCESS = 'TASKS_LOAD_CATEGORY_LIST_SUCCESS'

export const TASKS_ADD_TASK = 'TASKS_ADD_TASK'
export const TASKS_CHANGE_UPDATE_TASK_STATE = 'TASKS_CHANGE_UPDATE_TASK_STATE'

export const TASKS_UPDATE_TASK = 'TASKS_UPDATE_TASK'
export const TASKS_UPDATE_TASK_SUCCESS = 'TASKS_UPDATE_TASK_SUCCESS'
