export const TASKS_LOAD_TASK_LIST = 'TASKS_LOAD_TASK_LIST'
export const TASKS_LOAD_TASK_LIST_SUCCESS = 'TASKS_LOAD_TASK_LIST_SUCCESS'

export const TASKS_LOAD_CATEGORY_LIST = 'TASKS_LOAD_CATEGORY_LIST'
export const TASKS_LOAD_CATEGORY_LIST_SUCCESS = 'TASKS_LOAD_CATEGORY_LIST_SUCCESS'

export const TASKS_CHANGE_UPDATE_TASK_STATE = 'TASKS_CHANGE_UPDATE_TASK_STATE'

export const TASKS_UPDATE_TASK = 'TASKS_UPDATE_TASK'
export const TASKS_UPDATE_TASK_SUCCESS = 'TASKS_UPDATE_TASK_SUCCESS'

export const COMPLETE_SINGLE_TASK = 'COMPLETE_SINGLE_TASK'
export const COMPLETE_SINGLE_TASK_SUCCESS = 'COMPLETE_SINGLE_TASK_SUCCESS'
export const DELETE_SINGLE_TASK = 'DELETE_SINGLE_TASK'
export const DELETE_SINGLE_TASK_SUCCESS = 'DELETE_SINGLE_TASK_SUCCESS'
